- name: cart setup
  hosts: cart
  become: yes
  tasks:
  - name: disable nodejs
    ansible.builtin.command: dnf module disable nodejs -y

  - name: enable nodejs
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: install nodejs
    ansible.builtin.package:
      name: nodejs
      state: present

  - name: create roboshop system cart
    ansible.builtin.cart:
      name: roboshop
      comment: RoboShop System cart
      system: true
      shell: /sbin/nologin
      home: /app

  - name: create app directory
    ansible.builtin.file:
      state: directory
      path: /app
  - name: create app directory
    ansible.builtin.file:
      state: directory
      path: /app

  - name: download cart application
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/cart-v3.zip
      dest: /tmp/cart.zip

  - name: extract cart application
    ansible.builtin.unarchive:
      src: /tmp/cart.zip
      dest: /app
      remote_src: yes

  - name: install dependencies
    community.general.npm:
      path: /app

  - name: copy cart service
    ansible.builtin.copy:
      src: cart.service
      dest: /etc/systemd/system/cart.service

  - name: start and enable cart
    ansible.builtin.service:
      name: cart
      enabled: yes
      state: started