- name: configure dispatch server
  hosts: dispatch
  become: yes
  tasks:
  - name: install python package
    ansible.builtin.dnf:
      name: golang 
      state: present

  - name: create roboshop system user
    ansible.builtin.user:
      name: roboshop
      comment: RoboShop System user
      system: true
      shell: /sbin/nologin
      home: /app
  
  - name: remove app directory
    ansible.builtin.file:
      path: /app
      state: absent

  - name: create app directory
    ansible.builtin.file:
      state: directory
      path: /app

  - name: Delete dispatch file
    ansible.builtin.file:
      path: /tmp/dispatch.zip
      state: absent

  - name: download dispatch application
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/dispatch-v3.zip
      dest: /tmp/dispatch.zip

  - name: extract dispatch application
    ansible.builtin.unarchive:
      src: /tmp/dispatch.zip
      dest: /app
      remote_src: yes

  - name: install golang libraries
    ansible.builtin.command:
      name: "{{ item }}"
    loop:
    - go mod init dispatch
    - go get 
    - go build
    args:
      chdir: /app

  - name: copy dispatch service
    ansible.builtin.copy:
      src: dispatch.service
      dest: /etc/systemd/system/dispatch.service

  - name: daemon reload enable and start
    ansible.builtin.systemd_service:
      name: dispatch
      enabled: true
      state: started
      daemon_reload: true