- name: redis setup
  hosts: redis
  become: yes
  tasks:
  - name: disable default version
    ansible.builtin.command: dnf module disable redis -y
  
  - name:  enable redis version
    ansible.builtin.command: dnf module enable redis:7 -y

  - name: install redis
    ansible.builtin.package:
      name: redis
      state: present

  - name: allowing remote connections
    ansible.builtin.replace:
      path: /etc/redis/redis.conf
      regexp: 127.0.0.1 
      replace: 0.0.0.0 

  - name: replacing a line
    ansible.builtin.lineinfile:
    path: /etc/redis/redis.conf
    regexp: '^protected-mode yes'
    line: 'protected-mode no'

  - name: start and enable redis
    ansible.builtin.service:
      name: redis
      enabled: yes
      state: started